 name: Danger JS action
 on:
   pull_request:
     branches: [ master ]
 jobs:
   danger-js:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Checkout
       uses: actions/checkout@v2
     - name: Use Node.js
       uses: actions/setup-node@v1
     - run: npm ci
     - name: Danger
       run: npx danger-ts
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
