 name: Danger JS action
 on:
   pull_request:
     branches: [ master ]
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: npm ci
     - name: Danger
       run: npx danger-ts
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
